#! /bin/bash
source sketchpad_venv/bin/activate
nohup gunicorn -b 0.0.0.0:9091 -n Sketchpad \
    --access-logfile access.log \
    --error-logfile error.log \
    --log-level debug \
    --pid sketchpad.pid \
    --timeout 30 \
    --worker-class gthread \
    --workers 2 --threads 4 \
    wsgi:app > sketchpad.log &
